### ISSUE TITLE
Need help  (Persian version)

### ISSUE THREAD

**Issue by rezpower** [yuliskov/LeanKeyKeyboard#11]
This keyboard was a blessing as it allows me now to use and click on letters with a mouse on Nvidia Shield.
There is an Arabic version available but no Persian! The letters are they same for both languages except there are 4 extra letters in Persian (If I'm not wrong). Is there any chance you can release a Persian version please?

**Comment by yuliskov** [comment]
Hi. There already Persian. Just make sure that you've got the latest build from the release page.

**Comment by rezpower** [comment]
Thanks a lot for your quick reply :) I actually downloaded the keyboard from googleplay page!
Uninstalled it and installed from here as you suggested and all is working perfect (including persian) keyboard. Thanks again for your help and kindness. This keyboard is a life saver :) 🥇
