### ISSUE TITLE
Typing Special Characters in other Languages

### ISSUE THREAD

**Issue by mo123** [yuliskov/LeanKeyKeyboard#12]
Hi

In English you can long press on letters eg. 'e' to show the letter with special characters and choose which one you want.
But in other languages, if long pressing on letters, it doesn't show special characters for the letters or do anything.

**Comment by yuliskov** [comment]
Should be fixed here:
https://github.com/yuliskov/LeanKeyKeyboard/releases/download/5.2.7/LeanKeyKeyboardPro_v5.2.7_r.apk
