### ISSUE TITLE
AZERTY layout?

### ISSUE THREAD

**Issue by Kev63** [yuliskov/LeanKeyKeyboard#14]
Hi! I love this keyboard but how to change from QWERTY layout to AZERTY please? As French, it's a bit annoying to use EN layout. Thank you.

**Comment by yuliskov** [comment]
Do you still have a willing to add AZERTY layout?
I could tell you how to do it.

**Comment by shmox75** [comment]
> Do you still have a willing to add AZERTY layout?
> I could tell you how to do it.

Yes please I need AZERTY layout as french keyboard too

**Comment by yuliskov** [comment]
Added azerty layouts for English and French
https://github.com/yuliskov/LeanKeyKeyboard/releases/download/5.2.15/LeanKeyKeyboardPro_v5.2.15_r.apk

**Comment by shmox75** [comment]
> Added azerty layouts for English and French
> https://github.com/yuliskov/LeanKeyKeyboard/releases/download/5.2.15/LeanKeyKeyboardPro_v5.2.15_r.apk

Thank you

**Comment by yuliskov** [comment]
Done
