### ISSUE TITLE
Key size & color

### ISSUE THREAD

**Issue by Neuroquila-n8fall** [yuliskov/LeanKeyKeyboard#16]
The size of the keyboard is very tiny on some screens. This is an example of a screen with the dimensions 1024x600 on default display size:
![Screenshot_1566824439](https://user-images.githubusercontent.com/29146258/63692704-92d65f80-c812-11e9-870c-a324a4b077e1.png)

Also the highlight color of a selected key makes, in certain circumstances, a highlighted key very hard to spot.

Is there any possibility to change the highlight color? Or please point me to the file where the highlight color is configured.

**Comment by yuliskov** [comment]
Could you give me your device dpi?
This could be accomplished with AIDA.

**Comment by Neuroquila-n8fall** [comment]
I have a rather exotic screen resolution and DPI:
1024*600 @ 159DPI

**Comment by yuliskov** [comment]
OK. I'll test that. Thanks.

**Comment by yuliskov** [comment]
- fixed space key size on low dpi
https://github.com/yuliskov/LeanKeyKeyboard/releases/download/5.2.11/LeanKeyKeyboardPro_v5.2.11_r.apk

**Comment by yuliskov** [comment]
- Added option to increase keyboard size.
https://github.com/yuliskov/LeankeyKeyboard/releases

**Comment by Neuroquila-n8fall** [comment]
Great! This works for me. Thank you very much!
