### ISSUE TITLE
Swedish Language Support

### ISSUE THREAD

**Issue by Badkruka** [yuliskov/LeanKeyKeyboard#4]
Hello!
I would realy love if you add support for a Swedish keyboard. This app works realy well on Nvidia Shield but I am forced to use English since there is no support for Swedish.

**Comment by marvinorman** [comment]
I second this. Please add a Swedish language pack!

**Comment by yuliskov** [comment]
Many thanks. I'll try to add Swedish ASAP.

**Comment by Badkruka** [comment]
Thanks alot. :D

**Comment by marvinorman** [comment]
Yuliskov, how can I contact you? I can contribute

**Comment by yuliskov** [comment]
@marvinorman we could discuss details here in this thread

**Comment by marvinorman** [comment]
@yuliskov i need to send you some pictures on how leankey should look with swedish language

**Comment by yuliskov** [comment]
@marvinorman hmm, I don't see a problem. Images could be attached along with the post.

**Comment by marvinorman** [comment]
![leankey1](https://user-images.githubusercontent.com/16227672/42418350-bb96186c-829e-11e8-97b1-0530e3546da2.png)
![leankey2](https://user-images.githubusercontent.com/16227672/42418351-c09f7272-829e-11e8-962e-9ad0db912d1c.png)

**Comment by marvinorman** [comment]
Hope these pictures help with implementing a Swedish language pack. These pictures are from an Android TV box that automatically applies swedish language to Leankey based on system language. But Mi Box 3 and Nvidia Shield doesn't support this. That's why we need external language pack.

**Comment by yuliskov** [comment]
@marvinorman thanks for the helpful info

**Comment by yuliskov** [comment]
Seems, done. Please, remove any Google Play release first.

https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.14/LeanKeyKeyboardPro_v4.3.14_r.apk

**Comment by marvinorman** [comment]
@yuliskov Wow, works flawlessly. Thanks alot man!

The only thing i can see is that the "Search" button to the right of the keyboard was automatically translated to swedish with the google play version. But with this apk it says "Search" in english and doesn't translate.

Also, keyboard is defaulting to English language after reboot, and i have to manually switch to Swedish. 

Device: Mi Box 3

But other than these two small things, everything is awesome. Thanks again!

**Comment by Badkruka** [comment]
Thanks for the fast respond. :)
I made a clean install with the apk above on my Nvidia Shield TV and at first it seemed to be fine. The virtual keyboard on my TV was a Swedish one and it worked as intended but when I wrote on my physical keyboard it was the english version.

**Comment by yuliskov** [comment]
Update. 
Changes:
- remember selected kbd language upon reboot
https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.15/LeanKeyKeyboardPro_v4.3.15_r.apk

**Comment by marvinorman** [comment]
@yuliskov I uninstalled v. 4.3.14 and installed this, but now i'm only getting English language with this latest apk, anything im doing wrong?

**Comment by Badkruka** [comment]
Same here. I now only have english keyboard on both virtual and the physical.

**Comment by yuliskov** [comment]
@marvinorman @Badkruka 
Thanks for the quick feedback. 
Language dialog seems working now.
https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.17/LeanKeyKeyboardPro_v4.3.17_r.apk

**Comment by yuliskov** [comment]
Just in case someone want to fully localize keyboard to Swedish. Below the link to the translatable strings.
https://github.com/yuliskov/LeanKeyKeyboard/blob/master/leankeykeyboard/src/main/res/values/strings.xml

**Comment by marvinorman** [comment]
@yuliskov I can translate the strings for you, if you can implement them in the swedish kbd.

**Comment by Badkruka** [comment]
Thanks for the fast followups. :)
I have installed 4.3.17 now and the virtual keyboard works as intended and it still remains Swedish after I reboot. :)
But when I write on my physical keyboard it is still the English keyboard.

**Comment by yuliskov** [comment]
New release.
- add Swedish and other translations

https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.18/LeanKeyKeyboardPro_v4.3.18_r.apk

**Comment by marvinorman** [comment]
@yuliskov I decompiled the latest apk and translated the strings to Swedish. Everything works on point. 

[strings.zip](https://github.com/yuliskov/LeanKeyKeyboard/files/2207033/strings.zip)

**Comment by yuliskov** [comment]
@marvinorman good work. Thank you very much.

**Comment by marvinorman** [comment]
@yuliskov I noticed there were already Swedish strings available in "**values-sv**" folder.

**Comment by marvinorman** [comment]
@yuliskov I missed some buttons/text translations with previous strings file. I will upload the final one which is 100% everything correctly translated to Swedish.
[Strings (Swedish) (Final).zip](https://github.com/yuliskov/LeanKeyKeyboard/files/2207186/Strings.Swedish.Final.zip)

**Comment by yuliskov** [comment]
@marvinorman done
https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.20/LeanKeyKeyboardPro_v4.3.20_r.apk

**Comment by marvinorman** [comment]
@yuliskov Awesome, thanks for all your work!!

**Comment by yuliskov** [comment]
@Badkruka my kbd can't control physical kbd at all. I need to significantly rewrite the code to achieve this.

**Comment by Badkruka** [comment]
Oh ok I didn't know that.
Well thanks for the virtual one, it is realy nice and once again thanks for the time you spend giving us a Swedish translation. :D

**Comment by yuliskov** [comment]
@Badkruka speaking about physical keyboard. I seems found a way to accomplish what you want. There is a project called External Keyboard Helper (link below). Description says that it can change physical keyboard's layouts on-fly by shortcuts. But there is a problem. I can't get it worked. Maybe you'll have more luck.

Direct link to apk:
https://drive.google.com/uc?id=1uYBt3Fjyn-PGAo9O6BwgpErSOO32Zg7a
GPlay;
https://play.google.com/store/apps/details?id=com.apedroid.hwkeyboardhelperdemo
