### ISSUE TITLE
Add additional donation methods

### ISSUE THREAD

**Issue by user8446** [yuliskov/LeanKeyKeyboard#44]
Hello,

I tried to donate with the QIWI link you posted. I translated the site to English but the payment fails, possibly due to the international transaction.
I would be great if there were additional donation platforms such as PayPal, Liberapay, Ko-fi, Open Collective, etc. so that you can receive donations easily from other countries as well.

Thank you

**Comment by yuliskov** [comment]
Thx, I'll update soon.

**Comment by user8446** [comment]
Just letting you know I now see the PayPal option but it shows disabled:

![Screenshot 2022-01-20 190043](https://user-images.githubusercontent.com/18019245/150441436-eb64ff99-572a-44c1-a862-00acdad52316.jpg)

**Comment by user8446** [comment]
I see you added Patreon and PayPal directly. I just sent a donation through PayPal as I think the fees are a little less. 

Thank you for the development and maintaining LeanKeyKeyboard!

**Comment by yuliskov** [comment]
@user8446 wow. Thanks for generous donation, friend. It's really needed in such a tough times. BTW, both, Patreon and PayPal temporarily have disable fees in my country (Ukraine).

**Comment by user8446** [comment]
You're very welcome and wish the best for the people of Ukraine!
