### ISSUE TITLE
LeanKey App and all language packs show up as icons in the Leanback launcher

### ISSUE THREAD

**Issue by fktpa813** [yuliskov/LeanKeyKeyboard#5]
LeanKey App and all language packs show up in the "Apps" row in the Leanback launcher, even though they are not supposed to be executed as normal applications.
This happens because the app itself and language packs have [LEANBACK_LAUNCHER](https://developer.android.com/reference/android/content/Intent#CATEGORY_LEANBACK_LAUNCHER) intent indicated in the manifest.
Please remove the following line from [AndroidManifest.xml](https://github.com/yuliskov/LeanKeyKeyboard/blob/master/leankeykeyboard/src/main/AndroidManifest.xml) of the app and all lang packs:
`<category android:name="android.intent.category.LEANBACK_LAUNCHER"/>`

**Comment by yuliskov** [comment]
hi, @fktpa813 
All apps that published to Android TV store required to have such string in manifest. I cant change this.
But, you should give a try to the pro version. In this version all langs already presented in the main package.

**Comment by fktpa813** [comment]
Thanks - just found the pro version here, I'll give it a try!
