### ISSUE TITLE
Go to next line or add Enter key support if typing on AndroidTV

### ISSUE THREAD

**Issue by mo123** [yuliskov/LeanKeyKeyboard#6]
Is there a way to go to the next line when typing a document?
Eg. you type a text document in ES File Manager on AndroidTV Nougat/Oreo, now you want to go to the next line.
Can another character be added for such a thing to work with an ir remote?
Or if you use an airmouse with a keyboard on the other side, if you press Enter, can it go to the next line, at the moment Enter key has no action in a text file? Maybe it is an AndroidTV bug, not sure.

**Comment by yuliskov** [comment]
@mo123 thanks. I'll check the issue on my setup out and let you know.

**Comment by yuliskov** [comment]
update:
https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.25/LeanKeyKeyboardPro_v4.3.25_r.apk

**Comment by mo123** [comment]
Thanks, it works well now.

Just a small favor, is it possible to reduce the time the characters get highlighted by the mouse pointer?
If you move fast and quickly want to click on the characters to type something with an airmouse, mouse pointer remote then you need to wait 0.5-1 second before the next letter gets highlighted.
If the time or animation can be cut in half it will feel a lot faster.

**Comment by yuliskov** [comment]
@mo123 check the latest update
