### ISSUE TITLE
Issue in LeanKeyKeyboard Pro with language switcher on Android TV

### ISSUE THREAD

**Issue by tsynik** [yuliskov/LeanKeyKeyboard#7]
On Android TV firmwares LeanKeyKeyboard Pro (last 4.3.26 and previous releases) not always allow to switch to default language (EN). For example, in Nord VPN app when on Log In screen, I need to enter email, keyboard pops in Russian (system) language, and I can't switch to English by pressing Globe icon. If there is other additional languages defined (for example German) it pops as German layout and switched between German and Russian, but not English. As a fix, if we will have English in Language chooser as an option (selected), will it help avoid this bug? Seen this behavior in other apps / input fields too.

**Comment by yuliskov** [comment]
Thanks for the detailed report. Possible fixes has been added to the latest release.

**Comment by tsynik** [comment]
Looks like all works as it should on 4.2.27 and up. Thanks a lot!
