### ISSUE TITLE
Disable the error message when opening LeanKeyBoard banner in AndroidTV Nougat

### ISSUE THREAD

**Issue by mo123** [yuliskov/LeanKeyKeyboard#9]
On AndroidTV Nougat when you click on the LeanKeyKeyboard banner it says Android Manifest error.
Is it possible to make it just do nothing when opened or open the Language Input Settings in Android instead?

**Comment by mo123** [comment]
The error message is: 'Unable to find explicit activity class {com.android.settings/com.android.settings.Settings$InputMethodAndLanguageSettingActivity}; have you declared this activity in your AndroidManifest.xml?'

In AndroidTV, there is only TVSettings.apk, no Settings.apk, can that be the problem?
https://github.com/rock64-android/platform-packages-apps-TvSettings

**Comment by yuliskov** [comment]
@mo123 update: https://github.com/yuliskov/LeanKeyKeyboard/releases/download/4.3.30/LeanKeyKeyboardPro_v4.3.30_r.apk

**Comment by mo123** [comment]
Works perfect now.

**Comment by yuliskov** [comment]
@mo123 great, thanks!
